spring.application.name=CustomerManagement

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/customermanagement}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MyPassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false